# Generated by Django 4.2.15 on 2024-09-02 20:04

import django.contrib.postgres.search
from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('category', models.TextField()),
                ('content', models.TextField()),
                ('publication_country', models.CharField(max_length=100)),
                ('revenue_generated', models.CharField(max_length=255)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['search_vector'], name='search_vector_idx')],
            },
        ),
        migrations.CreateModel(
            name='MagazineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_id', models.IntegerField()),
                ('content', models.TextField()),
                ('vector_representation', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector_representation'], m=16, name='clip_l14_vectors_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
